nosleep_reddit_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
]

stories/urls.py
from django.urls import path, re_path
from . import views

app_name = 'stories'

urlpatterns = [
    path('', views.index, name='index'),
    path('submission/<str:submission_id>/',
         views.get_submission, name='submission'),
    path('<str:sort_by>/<int:page>/',
         views.get_10_more_submissions, name='next_submissions'),
    path('search/', views.search, name='search'),
    re_path(r'^', views.not_found, name='not_found'),
]

stories/models.py
from django.db import models

# Create your models here.

stories/views.py
from django.shortcuts import render
from .utilities import get_submissions, next_submissions, get_submission_info, search_submissions
import pprint
from django.http import JsonResponse
import json


def index(request):
    submissions = get_submissions()

    context = {
        'submissions': submissions,
    }

    return render(request, "stories/index.html", context)


def get_10_more_submissions(request, sort_by, page):
    submissions = next_submissions(sort_by, page)

    return JsonResponse(submissions, safe=False)


def get_submission(request, submission_id):

    submission = get_submission_info(submission_id)

    context = {
        'submission': submission
    }

    return render(request, "stories/submission.html", context)


def search(request):

    if request.method == 'POST':
        post_data = json.loads(request.body.decode('utf-8'))
        search_value = post_data['search']
        page = post_data['page']

        submissions = search_submissions(search_value, page)

        return JsonResponse(submissions, safe=False)

    return JsonResponse({}, safe=False)


def not_found(request):
    return render(request, "stories/not_found.html", {})

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NoSleep</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link
      rel="shortcut icon"
      type="image/jpg"
      href="{% static 'images/favicon.png' %}"
    />
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">{% block content %} {% endblock content %}</div>
    <script
      src="https://kit.fontawesome.com/8c0844d769.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar">
  <a href="{% url 'stories:index' %}"><h1>No Sleep</h1></a>
</nav>

templates/stories/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="controls">
    <span id="hot-submissions">
        <i class="fab fa-hotjar"></i><span style="display:inline; font-size: 14px; margin-right:0px">Hot</span>
    </span>
    <span id="new-submissions">
        <i class="fas fa-certificate"></i><span style="display:inline; font-size: 14px; margin-right:0px">New</span>
    </span>
    <span id="top-submissions">
        <i class="fas fa-signal"></i><span style="display:inline; font-size: 14px; margin-right:0px">Top</span>
    </span>
</div>
<div class="search-input">
  <div class="search-icon">
    <i class="fas fa-search"></i>
  </div>
  {% csrf_token %}
  <input type="text" id="submission-search" placeholder="Search"/>
</div>
<div id="submissions">
{% for submission in submissions %}
  <a class="submission-link" href="{% url 'stories:submission' submission.id %}">
  <div class="submission">
    <div class="detail">
      <p>
        Posted By: u/{{submission.author}}&nbsp;&nbsp;&nbsp;
        {{submission.posted_on }}
      </p>
    </div>
    <h4 class="submission-title">
      {% if submission.flair %}
      <span class="flair">{{ submission.flair }}</span>
      {% endif %} {{submission.title}}
    </h4>
    <p class="score">Upvotes: {{submission.score}}</p>
  </div>
  </a>
  {% endfor %}
</div>
<div id="load-more">
  <button id="load-more-btn">
    <img
      id="spinner"
      src="{% static 'images/spinner.gif' %}"
      alt=""
      class="hide"
      style="height: 25px"
    />
    <span id="btn-text">Load More<span />
  </button>
</div>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
  integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
  crossorigin="anonymous"
></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock content %}

templates/stories/not_found.html
{% extends 'base.html' %} {% block content %}
<h2>Page Not Found</h2>
{% endblock content %}

templates/stories/submission.html
{% extends 'base.html' %} {% block content %} {% if submission|length == 0 %}
<h1>Error 404. No Submission Found.</h1>
{%else%}
<div class="submission-container">
  <h3>{{ submission.title }}</h3>
  {% if submission.flair %}
  <span class="flair">{{ submission.flair }}</span>
  {% endif %}
  <div class="detail">
    <p>
      Posted By: u/{{submission.author}}&nbsp;&nbsp;&nbsp;
      {{submission.posted_on }}
    </p>
  </div>
  <div class="selftext">
    {% for paragraph in submission.selftext %}
    <p class="paragraph">{{paragraph}}</p>
    {% endfor %}
  </div>
</div>
{% endif %} {% endblock %}